services:
  mssql:
    container_name: w3resource_sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${HOME}/w3resource_sql/data:/tmp/csvdata